### ISSUE TITLE
citr addin not populated

### ISSUE THREAD

**Issue by alperyilmaz** [crsh/citr#14] opened 2017-08-18 11:33 UTC
Hi,
After citr installation the "insert citation" option is not found under Addin button. Package installation didn't give error so error might be beyond that.
How can I troubleshoot the problem? Is there any rstudio log file so that I can check what went wrong?
On the other side, I suspect that the problem might be home folder of user including non-ascii character "æ" , can this be the problem? I need to troubleshoot the problem but I don't have log file.

I'm suspecting about folder name issue because it caused trouble with Git integration, resulting in "Directory name is invalid" errors during commits in RStudio.

**Comment by crsh** [comment] 2017-08-18 12:27
Hi Alper,

thanks for reaching out. If this is indeed caused by the path to your home directory, I don't think this is something I could fix but may be related to RStudio. Could you first try restarting RStudio to see if that helps and verify that the package is correctly installed by loading it manually (`library("citr")`) and running `insert_citation()` from the command line?

**Comment by alperyilmaz** [comment] 2017-08-18 14:37
Hi.. Thanks for quick reply. `insert_citation()` works as expected, additional window opens.. So, this is definitely an RStudio problem but I don't know even where to begin..

**Comment by crsh** [comment] 2017-08-18 15:31
Could you also make sure that the addin is available when you click "Browse addins"? If it is try executing the addin from their. It appears that this has [helped others](https://support.rstudio.com/hc/en-us/community/posts/115008594608-Addins-toolbar-menu-not-populating-with-installed-addins).

If this is the case, the first thing I would do is update to the latest version of RStudio. If that doesn't help, try contacting their support (also see [here](https://support.rstudio.com/hc/en-us/community/posts/217939607-Add-in-toolbar-not-showing-after-install)). Should this turn out to be an issue in `citr` after all, I'll be more than happy to help you fix it. I'll close this issue for now. Feel free to reopen it.

**Closed as completed by crsh** 2017-08-18 15:31 UTC
